<?php

/**
 * Forge Fields import, export, settings, and feedback functionality.
 *
 * This file renders the Forge Fields Settings screen and handles
 * field-group JSON exports, JSON imports, and feedback submissions.
 */

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Render the Forge Fields Settings page.
 *
 * Displays the field-group export/import tools, feedback form,
 * and any status notices generated by those actions.
 */
function ff_render_settings_page()
{
    if (! current_user_can('manage_options')) {
        return;
    }

    $notice = isset($_GET['ff_notice'])
        ? sanitize_key(wp_unslash($_GET['ff_notice']))
        : '';

    $imported = isset($_GET['imported'])
        ? absint($_GET['imported'])
        : 0;

    $skipped = isset($_GET['skipped'])
        ? absint($_GET['skipped'])
        : 0;

?>
    <div class="wrap ff-admin ff-settings ff-has-brandbar">

        <?php if ($notice === 'imported') : ?>
            <div class="notice notice-success inline is-dismissible">
                <p>
                    <?php
                    printf(
                        'Field groups imported successfully. Imported: %d. Skipped: %d.',
                        absint($imported),
                        absint($skipped)
                    );
                    ?>
                </p>
            </div>
        <?php endif; ?>

        <?php if ($notice === 'invalid_file') : ?>
            <div class="notice notice-error inline is-dismissible">
                <p>The selected file is not a valid Forge Fields JSON export.</p>
            </div>
        <?php endif; ?>

        <?php if ($notice === 'upload_error') : ?>
            <div class="notice notice-error inline is-dismissible">
                <p>The JSON file could not be uploaded.</p>
            </div>
        <?php endif; ?>

        <?php if ($notice === 'feedback_sent') : ?>
            <div class="notice notice-success inline is-dismissible">
                <p>Your Forge Fields feedback was sent successfully.</p>
            </div>
        <?php endif; ?>

        <?php if ($notice === 'feedback_failed') : ?>
            <div class="notice notice-error inline is-dismissible">
                <p>Forge Fields could not send your feedback. Please try again later.</p>
            </div>
        <?php endif; ?>

        <?php if ($notice === 'feedback_empty') : ?>
            <div class="notice notice-error inline is-dismissible">
                <p>Please enter a feedback message before submitting.</p>
            </div>
        <?php endif; ?>

        <?php if ($notice !== '') : ?>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const url = new URL(window.location.href);

                    url.searchParams.delete('ff_notice');
                    url.searchParams.delete('imported');
                    url.searchParams.delete('skipped');

                    window.history.replaceState({},
                        document.title,
                        url.pathname + url.search + url.hash
                    );
                });
            </script>
        <?php endif; ?>

        <div class="ff-settings-grid">

            <div class="ff-settings-card">

                <h2>Export Field Groups</h2>

                <p>
                    Download all Forge Fields field-group definitions as a JSON file.
                    Saved field values are not included.
                </p>

                <form method="post">

                    <?php wp_nonce_field(
                        'ff_export_field_groups',
                        'ff_export_nonce'
                    ); ?>

                    <button
                        type="submit"
                        name="ff_export_field_groups"
                        value="1"
                        class="button button-primary">
                        Export JSON
                    </button>

                </form>

            </div>

            <div class="ff-settings-card">

                <h2>Import Field Groups</h2>

                <p>
                    Import field-group definitions from a Forge Fields JSON export.
                </p>

                <form
                    method="post"
                    enctype="multipart/form-data">

                    <?php wp_nonce_field(
                        'ff_import_field_groups',
                        'ff_import_nonce'
                    ); ?>

                    <div class="ff-settings-field">

                        <label for="ff_import_file">
                            JSON File
                        </label>

                        <input
                            type="file"
                            id="ff_import_file"
                            name="ff_import_file"
                            accept=".json,application/json"
                            required>

                    </div>

                    <div class="ff-settings-field">

                        <label for="ff_import_conflict">
                            Existing field groups
                        </label>

                        <div class="ff-select-wrap">

                            <select
                                id="ff_import_conflict"
                                name="ff_import_conflict">
                                <option value="skip">
                                    Skip existing
                                </option>

                                <option value="overwrite">
                                    Overwrite existing
                                </option>

                                <option value="duplicate">
                                    Create duplicates
                                </option>
                            </select>

                        </div>

                    </div>

                    <button
                        type="submit"
                        name="ff_import_field_groups"
                        value="1"
                        class="button button-primary">
                        Import JSON
                    </button>

                </form>

            </div>

            <div class="ff-settings-card">

                <h2>Feedback</h2>

                <p>
                    Found a bug, have an idea, or need help with Forge Fields?
                    Send us a message directly from WordPress.
                    Bug reports can include additional site information to help diagnose the issue.
                </p>

                <form method="post">

                    <?php wp_nonce_field(
                        'ff_submit_feedback',
                        'ff_feedback_nonce'
                    ); ?>

                    <div class="ff-settings-field">

                        <label for="ff_feedback_type">
                            Feedback Type
                        </label>

                        <div class="ff-select-wrap">
                            <select
                                id="ff_feedback_type"
                                name="ff_feedback_type">
                                <option value="general">General Inquiry</option>
                                <option value="feature">Feature Request</option>
                                <option value="bug">Bug Report</option>
                            </select>
                        </div>

                        <div
                            id="ff_feedback_bug_details"
                            style="display: none;padding-top: 15px;">

                            <div class="ff-settings-field">

                                <label for="ff_feedback_php_version">
                                    PHP Version
                                </label>

                                <input
                                    type="text"
                                    id="ff_feedback_php_version"
                                    name="ff_feedback_php_version"
                                    value="<?php echo esc_attr(PHP_VERSION); ?>">

                            </div>

                            <div class="ff-settings-field">

                                <label for="ff_feedback_plugin_version">
                                    Forge Fields Version
                                </label>

                                <input
                                    type="text"
                                    id="ff_feedback_plugin_version"
                                    name="ff_feedback_plugin_version"
                                    value="<?php echo esc_attr(
                                                defined('FF_VERSION')
                                                    ? FF_VERSION
                                                    : ''
                                            ); ?>">

                            </div>

                            <div class="ff-settings-field">

                                <label for="ff_feedback_site_url">
                                    Site URL
                                </label>

                                <input
                                    type="url"
                                    id="ff_feedback_site_url"
                                    name="ff_feedback_site_url"
                                    value="<?php echo esc_url(home_url()); ?>">

                            </div>

                        </div>

                    </div>

                    <div class="ff-settings-field">

                        <label for="ff_feedback_message">
                            Message
                        </label>

                        <textarea
                            id="ff_feedback_message"
                            name="ff_feedback_message"
                            rows="6"
                            class="large-text"
                            maxlength="3000"
                            required></textarea>

                    </div>

                    <button
                        type="submit"
                        name="ff_submit_feedback"
                        value="1"
                        class="button button-primary">
                        Submit Feedback
                    </button>

                </form>
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        const typeSelect = document.getElementById('ff_feedback_type');
                        const bugDetails = document.getElementById('ff_feedback_bug_details');

                        if (!typeSelect || !bugDetails) {
                            return;
                        }

                        function syncBugFields() {
                            bugDetails.style.display =
                                typeSelect.value === 'bug' ?
                                'block' :
                                'none';
                        }

                        syncBugFields();

                        typeSelect.addEventListener('change', syncBugFields);
                    });
                </script>
            </div>

        </div>

    </div>
<?php
}


/* EXPORT */
add_action('admin_init', 'ff_handle_field_group_export');

/**
 * Handle field-group JSON exports.
 *
 * Verifies the current user's permissions and export nonce, collects
 * all Forge Fields field-group definitions, removes transient metadata,
 * encodes the definitions as JSON, and sends the JSON as a download.
 */
function ff_handle_field_group_export()
{
    if (! current_user_can('manage_options')) {
        return;
    }

    if (! isset($_POST['ff_export_field_groups'])) {
        return;
    }

    check_admin_referer(
        'ff_export_field_groups',
        'ff_export_nonce'
    );

    $groups = ff_get_all_groups();

    /**
     * Remove runtime-only save timestamps from exported definitions.
     */
    foreach ($groups as &$group) {
        unset($group['last_saved']);
    }
    unset($group);

    $plugin_version = defined('FF_VERSION')
        ? FF_VERSION
        : 'unknown';

    $export = [
        'format'               => 'forge-fields',
        'signature'            => 'forge-fields-export',
        'schema_version'       => 1,
        'forge_fields_version' => $plugin_version,
        'exported_at'          => wp_date(
            'c',
            time(),
            wp_timezone()
        ),
        'field_groups'         => $groups,
    ];

    $json = wp_json_encode(
        $export,
        JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
    );

    if ($json === false) {
        wp_die('Forge Fields could not generate the JSON export.');
    }

    $filename = sprintf(
        'forge-fields-%s.json',
        wp_date(
            'Y-m-d-His',
            time(),
            wp_timezone()
        )
    );

    nocache_headers();

    header(
        'Content-Type: application/json; charset=utf-8'
    );

    header(
        'Content-Disposition: attachment; filename="' .
            $filename .
            '"'
    );

    header(
        'Content-Length: ' . strlen($json)
    );

    echo $json;
    exit;
}


/* IMPORT */
add_action('admin_init', 'ff_handle_field_group_import');

/**
 * Handle field-group JSON imports.
 *
 * Verifies permissions and the import nonce, validates the uploaded
 * JSON file, sanitizes imported field-group definitions, resolves
 * conflicts with existing groups, and saves the resulting definitions.
 */
function ff_handle_field_group_import()
{
    if (! current_user_can('manage_options')) {
        return;
    }

    if (! isset($_POST['ff_import_field_groups'])) {
        return;
    }

    check_admin_referer(
        'ff_import_field_groups',
        'ff_import_nonce'
    );

    $settings_url = admin_url(
        'admin.php?page=forge-fields-settings'
    );

    if (
        empty($_FILES['ff_import_file'])
        || ! isset($_FILES['ff_import_file']['error'])
        || $_FILES['ff_import_file']['error'] !== UPLOAD_ERR_OK
    ) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'upload_error',
                $settings_url
            )
        );

        exit;
    }

    $file = $_FILES['ff_import_file'];

    $filename = isset($file['name'])
        ? sanitize_file_name($file['name'])
        : '';

    $extension = strtolower(
        pathinfo($filename, PATHINFO_EXTENSION)
    );

    if ($extension !== 'json') {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'invalid_file',
                $settings_url
            )
        );

        exit;
    }

    if (
        ! empty($file['size'])
        && (int) $file['size'] > 2 * MB_IN_BYTES
    ) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'invalid_file',
                $settings_url
            )
        );

        exit;
    }

    $tmp_name = isset($file['tmp_name'])
        ? $file['tmp_name']
        : '';

    if (
        ! $tmp_name
        || ! is_uploaded_file($tmp_name)
    ) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'upload_error',
                $settings_url
            )
        );

        exit;
    }

    $json = file_get_contents($tmp_name);

    if ($json === false) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'invalid_file',
                $settings_url
            )
        );

        exit;
    }

    $data = json_decode($json, true);

    /**
     * Verify that the uploaded JSON matches a supported
     * Forge Fields export structure.
     *
     * Backward compatibility:
     * - Legacy schema-1 Forge Fields exports may not contain
     *   the newer signature value and are still accepted.
     * - Newer schema-1 exports must use the expected signature
     *   when a signature is present.
     */
    $is_forge_export =
        is_array($data)
        && ($data['format'] ?? '') === 'forge-fields'
        && isset($data['schema_version'])
        && (int) $data['schema_version'] === 1
        && isset($data['field_groups'])
        && is_array($data['field_groups']);

    $has_signature = isset($data['signature']);

    $has_valid_signature =
        ! $has_signature
        || $data['signature'] === 'forge-fields-export';

    if (
        ! $is_forge_export
        || ! $has_valid_signature
    ) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'invalid_file',
                $settings_url
            )
        );

        exit;
    }

    /**
     * Validate the structure of every imported Forge Fields group
     * before any existing data is modified.
     *
     * Schema 1 compatibility rules are intentionally conservative:
     * - A group must be an array.
     * - Its ID may come from either the group's id property or its array key.
     * - A title must be present.
     * - Location must be one of the supported Forge Fields locations.
     * - Fields must be provided as an array, but the array may be empty.
     *
     * Newer optional field properties are not required here so exports
     * from older Forge Fields versions remain compatible.
     */
    $valid_group_structure = true;

    foreach ($data['field_groups'] as $group_key => $group) {

        if (! is_array($group)) {
            $valid_group_structure = false;
            break;
        }

        $group_id = ! empty($group['id'])
            ? sanitize_text_field((string) $group['id'])
            : sanitize_text_field((string) $group_key);

        if ($group_id === '') {
            $valid_group_structure = false;
            break;
        }

        if (
            ! isset($group['title'])
            || ! is_scalar($group['title'])
        ) {
            $valid_group_structure = false;
            break;
        }

        if (
            ! isset($group['location'])
            || ! is_scalar($group['location'])
            || ! in_array(
                sanitize_key((string) $group['location']),
                ['page', 'post', 'global'],
                true
            )
        ) {
            $valid_group_structure = false;
            break;
        }

        if (
            ! isset($group['fields'])
            || ! is_array($group['fields'])
        ) {
            $valid_group_structure = false;
            break;
        }
    }

    if (! $valid_group_structure) {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'invalid_file',
                $settings_url
            )
        );

        exit;
    }

    /**
     * Strictly validate field types in modern signed Forge Fields exports.
     *
     * Signed exports are generated by a known Forge Fields schema, so an
     * unknown field type indicates that the file has been altered or is not
     * valid for the current schema.
     *
     * Legacy unsigned schema-1 exports remain tolerant for backward
     * compatibility and are normalized later during import.
     */
    if ($has_signature) {

        $allowed_signed_field_types = [
            'text',
            'textarea',
            'number',
            'email',
            'url',
            'range',
            'password',
            'image',
            'file',
            'wysiwyg',
            'select',
            'checkbox',
            'radio',
            'button_group',
            'true_false',
            'tab',
        ];

        $valid_signed_fields = true;

        foreach ($data['field_groups'] as $group) {

            foreach ($group['fields'] as $field) {

                if (
                    ! is_array($field)
                    || ! isset($field['type'])
                    || ! is_scalar($field['type'])
                ) {
                    $valid_signed_fields = false;
                    break 2;
                }

                $field_type = sanitize_key(
                    (string) $field['type']
                );

                if (
                    ! in_array(
                        $field_type,
                        $allowed_signed_field_types,
                        true
                    )
                ) {
                    $valid_signed_fields = false;
                    break 2;
                }
            }
        }

        if (! $valid_signed_fields) {
            wp_safe_redirect(
                add_query_arg(
                    'ff_notice',
                    'invalid_file',
                    $settings_url
                )
            );

            exit;
        }
    }

    $conflict_mode = isset($_POST['ff_import_conflict'])
        ? sanitize_key(
            wp_unslash($_POST['ff_import_conflict'])
        )
        : 'skip';

    if (
        ! in_array(
            $conflict_mode,
            ['skip', 'overwrite', 'duplicate'],
            true
        )
    ) {
        $conflict_mode = 'skip';
    }

    $existing_groups = ff_get_all_groups();

    $imported = 0;
    $skipped  = 0;

    foreach ($data['field_groups'] as $group_key => $group) {

        if (! is_array($group)) {
            $skipped++;
            continue;
        }

        $import_id = ! empty($group['id'])
            ? sanitize_text_field($group['id'])
            : sanitize_text_field($group_key);

        if ($import_id === '') {
            $skipped++;
            continue;
        }

        $group['id'] = $import_id;

        $group['title'] = isset($group['title'])
            ? sanitize_text_field($group['title'])
            : '(no title)';

        $group['location'] = isset($group['location'])
            ? sanitize_key($group['location'])
            : 'page';

        $location_target = isset($group['location_target'])
            ? absint($group['location_target'])
            : 0;

        $group['location_target'] = $location_target
            ? (string) $location_target
            : '';

        $group['status'] = isset($group['status'])
            ? sanitize_key($group['status'])
            : 'active';

        if (! in_array($group['location'], ['page', 'post', 'global'], true)) {
            $group['location'] = 'page';
        }

        if (! in_array($group['status'], ['active', 'inactive', 'trash'], true)) {
            $group['status'] = 'active';
        }

        $sanitized_fields = [];

        if (
            isset($group['fields'])
            && is_array($group['fields'])
        ) {
            foreach ($group['fields'] as $field) {

                if (! is_array($field)) {
                    continue;
                }

                $field_name = isset($field['name'])
                    ? substr(
                        sanitize_key($field['name']),
                        0,
                        50
                    )
                    : '';

                $field_label = isset($field['label'])
                    ? substr(
                        sanitize_text_field($field['label']),
                        0,
                        50
                    )
                    : '';

                $field_type = isset($field['type'])
                    ? sanitize_key($field['type'])
                    : 'text';

                $allowed_types = [
                    'text',
                    'textarea',
                    'number',
                    'email',
                    'url',
                    'range',
                    'password',
                    'image',
                    'file',
                    'wysiwyg',
                    'select',
                    'checkbox',
                    'radio',
                    'button_group',
                    'true_false',
                    'tab',
                ];

                if (! in_array($field_type, $allowed_types, true)) {
                    $field_type = 'text';
                }

                /*
         * Tab fields don't require a field name.
         */
                if ($field_type !== 'tab' && $field_name === '') {
                    continue;
                }

                if ($field_label === '') {
                    continue;
                }

                /**
                 * Preserve supported Forge Fields schema-1 field options.
                 *
                 * Missing options receive safe defaults so older exports
                 * continue to import correctly.
                 */
                $default_value = isset($field['default_value'])
                    ? sanitize_text_field(
                        (string) $field['default_value']
                    )
                    : '';

                $required = ! empty($field['required'])
                    ? 1
                    : 0;

                $character_limit = isset($field['character_limit'])
                    ? absint($field['character_limit'])
                    : 0;

                $prepend = isset($field['prepend'])
                    ? sanitize_text_field(
                        (string) $field['prepend']
                    )
                    : '';

                $append = isset($field['append'])
                    ? sanitize_text_field(
                        (string) $field['append']
                    )
                    : '';

                $prepend_append_types = [
                    'text',
                    'number',
                    'email',
                    'password',
                ];

                if (! in_array($field_type, $prepend_append_types, true)) {
                    $prepend = '';
                    $append  = '';
                }

                $character_limit_types = [
                    'text',
                    'textarea',
                    'email',
                    'url',
                    'password',
                ];

                if (! in_array($field_type, $character_limit_types, true)) {
                    $character_limit = 0;
                }

                $clean_field = [
                    'name'            => $field_name,
                    'label'           => $field_label,
                    'type'            => $field_type,
                    'default_value'   => $default_value,
                    'required'        => $required,
                    'character_limit' => $character_limit,
                    'prepend'         => $prepend,
                    'append'          => $append,
                ];

                if (
                    in_array(
                        $field_type,
                        ['select', 'checkbox', 'radio', 'button_group'],
                        true
                    )
                ) {
                    $choices = isset($field['choices'])
                        ? sanitize_textarea_field(
                            (string) $field['choices']
                        )
                        : '';

                    $clean_field['choices'] = $choices;
                }

                if ($field_type === 'range') {

                    if (isset($field['min']) && is_numeric($field['min'])) {
                        $clean_field['min'] = (float) $field['min'];
                    }

                    if (isset($field['max']) && is_numeric($field['max'])) {
                        $clean_field['max'] = (float) $field['max'];
                    }

                    if (isset($field['step']) && is_numeric($field['step'])) {
                        $clean_field['step'] = (float) $field['step'];
                    }
                }

                $sanitized_fields[] = $clean_field;
            }
        }

        $group['fields'] = $sanitized_fields;

        $group['last_saved'] = time();

        $already_exists = isset(
            $existing_groups[$import_id]
        );

        if (
            $already_exists
            && $conflict_mode === 'skip'
        ) {
            $skipped++;
            continue;
        }

        if (
            $already_exists
            && $conflict_mode === 'duplicate'
        ) {
            $new_id = ff_generate_group_id();

            $group['id'] = $new_id;

            $group['title'] .= ' (Imported Copy)';

            $existing_groups[$new_id] = $group;

            $imported++;
            continue;
        }

        $existing_groups[$import_id] = $group;

        $imported++;
    }

    ff_save_all_groups($existing_groups);

    $redirect_url = add_query_arg(
        [
            'ff_notice' => 'imported',
            'imported'  => $imported,
            'skipped'   => $skipped,
        ],
        $settings_url
    );

    wp_safe_redirect($redirect_url);
    exit;
}

/* SUBMIT FEEDBACK */
add_action('admin_init', 'ff_handle_feedback_submission');

/**
 * Handle Forge Fields feedback submissions.
 *
 * Verifies permissions and the feedback nonce, sanitizes the submitted
 * feedback, and sends it to the Forge Fields feedback service.
 */
function ff_handle_feedback_submission()
{
    if (! current_user_can('manage_options')) {
        return;
    }

    if (! isset($_POST['ff_submit_feedback'])) {
        return;
    }

    check_admin_referer(
        'ff_submit_feedback',
        'ff_feedback_nonce'
    );

    $settings_url = admin_url(
        'admin.php?page=forge-fields-settings'
    );

    $type = isset($_POST['ff_feedback_type'])
        ? sanitize_key(
            wp_unslash($_POST['ff_feedback_type'])
        )
        : 'general';

    $allowed_types = [
        'bug',
        'feature',
        'general',
    ];

    if (! in_array($type, $allowed_types, true)) {
        $type = 'general';
    }

    $message = isset($_POST['ff_feedback_message'])
        ? sanitize_textarea_field(
            wp_unslash($_POST['ff_feedback_message'])
        )
        : '';

    if ($message === '') {
        wp_safe_redirect(
            add_query_arg(
                'ff_notice',
                'feedback_empty',
                $settings_url
            )
        );

        exit;
    }

    $current_user = wp_get_current_user();

    $payload = [
        'type'       => $type,
        'message'    => $message,
        'user_email' => sanitize_email(
            $current_user->user_email
        ),
    ];

    if ($type === 'bug') {

        $php_version = isset($_POST['ff_feedback_php_version'])
            ? sanitize_text_field(
                wp_unslash($_POST['ff_feedback_php_version'])
            )
            : PHP_VERSION;

        $plugin_version = isset($_POST['ff_feedback_plugin_version'])
            ? sanitize_text_field(
                wp_unslash($_POST['ff_feedback_plugin_version'])
            )
            : (
                defined('FF_VERSION')
                ? FF_VERSION
                : 'Unknown'
            );

        $site_url = isset($_POST['ff_feedback_site_url'])
            ? esc_url_raw(
                wp_unslash($_POST['ff_feedback_site_url'])
            )
            : home_url();

        $payload['plugin_version'] = $plugin_version;
        $payload['wordpress_version'] = get_bloginfo('version');
        $payload['php_version'] = $php_version;
        $payload['site_url'] = $site_url;
    }

    $response = wp_remote_post(
        'https://forge-fields-feedback.useforgedev.workers.dev/',
        [
            'timeout' => 15,
            'headers' => [
                'Content-Type' => 'application/json',
            ],
            'body' => wp_json_encode($payload),
        ]
    );

    $sent = false;

    if (is_wp_error($response)) {

        error_log(
            'Forge Fields feedback request failed: ' .
                $response->get_error_message()
        );
    } else {

        $status_code = wp_remote_retrieve_response_code($response);

        $response_body = json_decode(
            wp_remote_retrieve_body($response),
            true
        );

        $sent =
            $status_code >= 200
            && $status_code < 300
            && is_array($response_body)
            && ! empty($response_body['success']);

        if (! $sent) {
            error_log(
                'Forge Fields feedback service returned an unsuccessful response.'
            );
        }
    }

    wp_safe_redirect(
        add_query_arg(
            'ff_notice',
            $sent
                ? 'feedback_sent'
                : 'feedback_failed',
            $settings_url
        )
    );

    exit;
}

/**
 * Log WordPress mail failures related to feedback delivery.
 */
add_action('wp_mail_failed', function ($error) {
    error_log(
        'Forge Fields wp_mail error: ' .
            $error->get_error_message()
    );
});
